25-Aug-22 17:23:52 - INFO - Start data:
 - url: https://khashtamov.com/ru/python-requests/
 - path: /home/ulitka/python-project-lvl3
25-Aug-22 17:23:53 - INFO - The page recording completed. Starting to work with resources.

25-Aug-22 17:23:53 - ERROR - File exist error:Traceback (most recent call last):
  File "/home/ulitka/python-project-lvl3/page_loader/work_with_files.py", line 42, in prepare_dir
  [Errno 17] File exists: '/home/ulitka/python-project-lvl3/khashtamov-com-ru-python-requests_files' (<class 'FileExistsError'>)
25-Aug-22 17:23:53 - WARNING - The program was completed. Exit Code is 2.
