21-Aug-22 01:10:39 - INFO - Start data:
url https://docs.pytest.org/en/7.1.x/_modules/_pytest/tmpdir.html
path /home/ulitka/python-project-lvl3
21-Aug-22 01:10:39 - INFO - The page recording completed. Starting to work with resources.

21-Aug-22 01:10:39 - ERROR - File exist error:Traceback (most recent call last):
  File "/home/ulitka/python-project-lvl3/page_loader/work_with_files.py", line 42, in prepare_dir
  [Errno 17] File exists: '/home/ulitka/python-project-lvl3/docs-pytest-org-en-7-1-x-_modules-_pytest-tmpdir_files' (<class 'FileExistsError'>)
21-Aug-22 01:10:39 - WARNING - The program was completed. Exit Code is 2.
